# .ai-context.yaml
# AI 어시스턴트가 프로젝트를 이해하기 위한 메타데이터
# tok_mcp 기반 아키텍처 컨텍스트 파일

project:
  name: abtsscm_backend
  description: 결혼 매칭 서비스 마이크로서비스 백엔드
  type: microservices
  language: python
  version: "1.0.0"
  domain: www.abysscm.com
  admin_domain: admin.abysscm.com

architecture:
  pattern: microservices
  container: docker-compose

  services:
    - name: login-service
      port: 8000
      responsibility: "인증 및 세션 관리 (일반 회원 + 관리자)"
      entrypoint: login-service/main.py
      dependencies:
        - user-service
      features:
        - 카카오 OAuth 로그인
        - JWT 토큰 발급
        - 관리자 인증 (허용된 카카오 계정만)

    - name: user-service
      port: 8001
      responsibility: "회원 정보 CRUD, 매칭 관리, 상담/만남 관리"
      entrypoint: user-service/main.py
      database: PostgreSQL
      external_services:
        - AWS S3
      features:
        - 회원 CRUD
        - 매칭 관리
        - 회원 필터링 검색
        - 회원 탈퇴/추방
        - 통계 대시보드
        - 상담 요청/관리
        - 만남 일정/후기 관리

    - name: pay-service
      port: 8002
      responsibility: "결제 처리 (토스페이먼츠)"
      entrypoint: pay-service/main.py
      dependencies:
        - user-service
      external_services:
        - Toss Payments API
      features:
        - 결제 준비/승인
        - 결제 내역 조회
        - 회원 등급 업데이트

    - name: place-service
      port: 8003
      responsibility: "데이트 장소 큐레이팅 (네이버 지도)"
      entrypoint: place-service/main.py
      database: PostgreSQL
      external_services:
        - Naver Local Search API
      features:
        - 장소 검색 (네이버 API)
        - 카테고리 기반 추천
        - 데이트 코스 생성/공유
        - 장소 정보 캐싱

    - name: notification-service
      port: 8004
      responsibility: "푸시 알림 관리 (FCM)"
      entrypoint: notification-service/main.py
      database: PostgreSQL
      external_services:
        - Firebase Cloud Messaging
      features:
        - FCM 토큰 등록/삭제
        - 푸시 알림 전송
        - 배치 알림 전송
        - 알림 목록/읽음 처리

    - name: chat-service
      port: 8005
      responsibility: "실시간 채팅 (WebSocket)"
      entrypoint: chat-service/main.py
      database: PostgreSQL
      external_services:
        - AWS S3
        - notification-service
      features:
        - WebSocket 실시간 채팅
        - 채팅방 생성/관리
        - 텍스트/이미지 메시지
        - 읽음 처리
        - 타이핑 인디케이터

technology_stack:
  framework: FastAPI
  runtime: Python 3.11
  orm: SQLAlchemy
  database: PostgreSQL (AWS RDS)
  container: Docker Compose
  cloud: AWS
  payment: Toss Payments

key_files:
  database:
    - path: user-service/db.py
      description: "DB 연결 설정 및 SQLAlchemy 모델 정의"

  authentication:
    - path: login-service/main.py
      description: "카카오 OAuth 로그인 처리 (일반/관리자)"
    - path: login-service/jwt_utils.py
      description: "JWT 생성 및 검증 유틸리티"

  user_management:
    - path: user-service/main.py
      description: "회원 CRUD, 매칭, 관리자 API"

  payment:
    - path: pay-service/main.py
      description: "토스페이먼츠 결제 처리"

  place_curation:
    - path: place-service/main.py
      description: "장소 검색 및 코스 관리 API"
    - path: place-service/db.py
      description: "장소/코스 DB 모델 정의"
    - path: place-service/naver_api.py
      description: "네이버 지역 검색 API 연동"

  notification:
    - path: notification-service/main.py
      description: "FCM 푸시 알림 API"
    - path: notification-service/fcm.py
      description: "Firebase Cloud Messaging 연동"

  chat:
    - path: chat-service/main.py
      description: "채팅 REST API + WebSocket"
    - path: chat-service/db.py
      description: "채팅방/메시지 DB 모델"
    - path: chat-service/connection.py
      description: "WebSocket 연결 관리자"

  configuration:
    - path: docker-compose.yml
      description: "서비스 오케스트레이션 설정"

data_models:
  User:
    table: users
    primary_key: user_id (카카오 ID)
    fields:
      - name: String(50) - 이름
      - email: String(100) - 이메일
      - phone_number: String(20) - 전화번호
      - age: String(3) - 나이
      - gender: String(2) - 성별 (남/여)
      - birth_date: String(30) - 생년월일 문자열
      - matching_count: Integer - 매칭 횟수
      - status: String(10) - 상태 (매칭전/매칭중/성혼/만료)
      - first_consultation: DateTime - 최초 상담일
      - last_consultation: DateTime - 마지막 상담일
      - consultation_count: Integer - 상담 횟수
      - matched_partner: BigInteger - 매칭된 상대 ID
      - membership_type: String(10) - 회원 등급 (일반회원/정회원/결제회원)
      - payment_date: DateTime - 결제일
      - is_banned: Boolean - 추방 여부
      - banned_at: DateTime - 추방일
      - deleted_at: DateTime - 탈퇴일 (소프트 삭제)

  Admin:
    table: admins
    primary_key: admin_id
    fields:
      - kakao_id: BigInteger - 허용된 카카오 ID
      - name: String(50) - 관리자 이름
      - role: String(20) - 역할 (super_admin/admin)
      - created_at: DateTime - 생성일

  Consultation:
    table: consultations
    primary_key: id
    fields:
      - user_id: BigInteger - 요청 회원 ID
      - requested_date: Date - 희망 상담일
      - requested_time: String(10) - 희망 시간
      - consultation_type: String(20) - 초기상담/매칭상담/사후상담
      - description: Text - 상담 내용
      - status: String(20) - 요청됨/확인됨/완료됨/취소됨
      - admin_note: Text - 관리자 메모
      - confirmed_date: Date - 확정 상담일
      - confirmed_time: String(10) - 확정 시간

  Meeting:
    table: meetings
    primary_key: id
    fields:
      - user_id: BigInteger - 요청 회원 ID
      - partner_id: BigInteger - 상대 회원 ID
      - meeting_date: Date - 만남 날짜
      - meeting_time: String(10) - 만남 시간
      - location: String(200) - 만남 장소
      - status: String(20) - 예약됨/완료됨/취소됨

  MeetingReview:
    table: meeting_reviews
    primary_key: id
    fields:
      - meeting_id: Integer - 만남 ID
      - reviewer_id: BigInteger - 작성자 ID
      - reviewed_id: BigInteger - 평가 대상 ID
      - rating: Integer - 1-5점 평가
      - content: Text - 후기 내용
      - next_meeting_intent: String(20) - 원함/미정/원하지않음
      - is_private: Boolean - 관리자만 열람

  DatePlace:
    table: date_places
    primary_key: id
    fields:
      - naver_place_id: String(100) - 네이버 장소 ID
      - name: String(200) - 장소명
      - category: String(100) - 카테고리
      - address: String(500) - 주소
      - latitude: Float - 위도
      - longitude: Float - 경도

  DateCourse:
    table: date_courses
    primary_key: id
    fields:
      - creator_id: BigInteger - 생성자 ID
      - title: String(200) - 코스 제목
      - description: Text - 코스 설명
      - is_shared: Boolean - 공유 여부
      - shared_with: BigInteger - 공유 대상 ID
      - status: String(20) - 작성중/완성/사용됨

  UserProfile:
    table: user_profiles
    primary_key: id
    fields:
      - user_id: BigInteger - 사용자 ID (unique)
      - height: Integer - 키 (cm)
      - job: String(100) - 직업
      - company: String(100) - 회사/학교
      - education: String(50) - 학력
      - religion: String(20) - 종교
      - smoking: String(20) - 흡연 여부
      - drinking: String(20) - 음주 여부
      - mbti: String(4) - MBTI
      - hobbies: Text - 취미 (JSON 배열)
      - introduction: Text - 자기소개
      - ideal_age_min/max: Integer - 이상형 나이 범위
      - ideal_height_min/max: Integer - 이상형 키 범위
      - ideal_location: String(100) - 선호 지역
      - ideal_religion: String(20) - 선호 종교
      - ideal_smoking: String(20) - 선호 흡연 여부

  UserPhoto:
    table: user_photos
    primary_key: id
    fields:
      - user_id: BigInteger - 사용자 ID
      - photo_url: String(500) - S3 URL
      - photo_type: String(20) - profile/additional
      - order_index: Integer - 순서
      - is_approved: Boolean - 관리자 승인 여부

  ChatRoom:
    table: chat_rooms
    primary_key: id
    fields:
      - user1_id: BigInteger - 사용자 1 ID
      - user2_id: BigInteger - 사용자 2 ID
      - is_active: Boolean - 활성 여부
      - last_message_at: DateTime - 마지막 메시지 시간

  Message:
    table: messages
    primary_key: id
    fields:
      - room_id: Integer - 채팅방 ID
      - sender_id: BigInteger - 발신자 ID
      - content: Text - 메시지 내용
      - message_type: String(20) - text/image
      - image_url: String(500) - 이미지 URL
      - is_read: Boolean - 읽음 여부

  SuccessStory:
    table: success_stories
    primary_key: id
    fields:
      - user1_id: BigInteger - 사용자 1 ID
      - user2_id: BigInteger - 사용자 2 ID
      - title: String(200) - 제목
      - content: Text - 내용
      - photo_url: String(500) - 커플 사진
      - is_public: Boolean - 공개 여부
      - display_names: String(100) - 표시 이름
      - status: String(20) - draft/pending/approved/rejected

  Referral:
    table: referrals
    primary_key: id
    fields:
      - referrer_id: BigInteger - 추천한 사람 ID
      - referee_id: BigInteger - 추천받은 사람 ID
      - referral_code: String(20) - 추천 코드
      - reward_status: String(20) - pending/eligible/rewarded
      - reward_type: String(50) - 보상 유형

api_endpoints:
  login-service:
    public:
      - method: POST
        path: /login/kakao
        description: "카카오 인증 코드로 로그인"
      - method: POST
        path: /submit
        description: "회원가입 정보 제출"
    admin:
      - method: POST
        path: /admin/login/kakao
        description: "관리자 카카오 로그인 (허용된 계정만)"
      - method: GET
        path: /admin/verify
        description: "관리자 JWT 토큰 검증"

  user-service:
    public:
      - method: POST
        path: /users/login-or-register
        description: "로그인 또는 등록 확인"
      - method: POST
        path: /users/add
        description: "새 회원 추가"
      - method: GET
        path: /users/{kakao_id}
        description: "회원 정보 조회"
      - method: PATCH
        path: /users/{user_id}/membership
        description: "회원 등급 업데이트"
    consultation:
      - method: POST
        path: /consultations
        description: "상담 요청 생성"
      - method: GET
        path: /consultations/my
        description: "내 상담 목록"
      - method: GET
        path: /consultations/{id}
        description: "상담 상세 조회"
      - method: PUT
        path: /consultations/{id}/cancel
        description: "상담 취소"
    meeting:
      - method: POST
        path: /meetings
        description: "만남 일정 생성"
      - method: GET
        path: /meetings/my
        description: "내 만남 목록"
      - method: GET
        path: /meetings/{id}
        description: "만남 상세 조회"
      - method: PUT
        path: /meetings/{id}/complete
        description: "만남 완료 처리"
      - method: PUT
        path: /meetings/{id}/cancel
        description: "만남 취소"
      - method: POST
        path: /meetings/{id}/reviews
        description: "만남 후기 작성"
    admin:
      - method: GET
        path: /admin/users
        description: "전체 회원 목록"
      - method: GET
        path: /admin/users/search
        description: "회원 필터링 조회"
        params:
          - status: 매칭전/매칭중/성혼/만료
          - membership_type: 일반회원/정회원/결제회원
          - gender: 남/여
          - has_payment: true/false
          - is_matched: true/false
      - method: GET
        path: /admin/users/{user_id}
        description: "회원 상세 조회"
      - method: PUT
        path: /admin/users/memo/{user_id}
        description: "회원 메모 저장 (S3)"
      - method: GET
        path: /admin/users/memo/{user_id}
        description: "회원 메모 조회 (S3)"
      - method: POST
        path: /admin/users/match/{user_id}/{partner_id}
        description: "회원 매칭 처리"
      - method: DELETE
        path: /admin/users/match/{user_id}
        description: "매칭 해제"
      - method: GET
        path: /admin/users/candidates/{user_id}
        description: "매칭 후보자 목록 조회 (이성, 매칭전 상태)"
      - method: DELETE
        path: /admin/users/{user_id}
        description: "회원 탈퇴 처리 (소프트 삭제)"
      - method: POST
        path: /admin/users/{user_id}/ban
        description: "회원 추방 (블랙리스트)"
      - method: GET
        path: /admin/stats
        description: "통계 대시보드"
      - method: GET
        path: /admin/consultations
        description: "전체 상담 목록"
      - method: PUT
        path: /admin/consultations/{id}/confirm
        description: "상담 확정"
      - method: PUT
        path: /admin/consultations/{id}/complete
        description: "상담 완료 처리"
      - method: GET
        path: /admin/meetings
        description: "전체 만남 목록"
      - method: GET
        path: /admin/reviews
        description: "전체 후기 열람"
      - method: GET
        path: /admin/meetings/stats
        description: "만남 통계"

  pay-service:
    public:
      - method: POST
        path: /payments/ready
        description: "결제 준비 (토스페이먼츠)"
      - method: POST
        path: /payments/confirm
        description: "결제 승인"
      - method: GET
        path: /payments/{payment_key}
        description: "결제 내역 조회"
      - method: GET
        path: /health
        description: "헬스체크"

  place-service:
    search:
      - method: GET
        path: /places/search
        description: "장소 검색 (네이버 API)"
        params:
          - query: 검색어
          - display: 결과 개수 (1-5)
      - method: GET
        path: /places/category
        description: "카테고리 기반 장소 검색"
        params:
          - location: 위치 (강남, 홍대 등)
          - category: 카테고리 (카페, 레스토랑 등)
      - method: GET
        path: /places/categories
        description: "사용 가능한 카테고리 목록"
      - method: GET
        path: /places/{place_id}
        description: "캐싱된 장소 상세 정보"
    course:
      - method: POST
        path: /courses
        description: "데이트 코스 생성"
      - method: GET
        path: /courses/my
        description: "내 코스 목록"
      - method: GET
        path: /courses/shared
        description: "공유받은 코스 목록"
      - method: GET
        path: /courses/{course_id}
        description: "코스 상세 (장소 포함)"
      - method: POST
        path: /courses/{course_id}/places
        description: "코스에 장소 추가"
      - method: DELETE
        path: /courses/{course_id}/places/{place_id}
        description: "코스에서 장소 제거"
      - method: POST
        path: /courses/{course_id}/share
        description: "매칭 상대와 코스 공유"
      - method: PUT
        path: /courses/{course_id}/complete
        description: "코스 완성 처리"
      - method: DELETE
        path: /courses/{course_id}
        description: "코스 삭제"
      - method: GET
        path: /health
        description: "헬스체크"

  notification-service:
    device:
      - method: POST
        path: /devices/register
        description: "FCM 토큰 등록"
      - method: DELETE
        path: /devices/{token}
        description: "FCM 토큰 삭제"
    notification:
      - method: POST
        path: /send
        description: "알림 전송 (내부용)"
      - method: POST
        path: /send/batch
        description: "배치 알림 전송"
      - method: GET
        path: /notifications/my
        description: "내 알림 목록"
      - method: PUT
        path: /notifications/{id}/read
        description: "알림 읽음 처리"
      - method: GET
        path: /health
        description: "헬스체크"

  chat-service:
    room:
      - method: POST
        path: /rooms
        description: "채팅방 생성"
      - method: GET
        path: /rooms
        description: "내 채팅방 목록"
      - method: GET
        path: /rooms/{room_id}/messages
        description: "메시지 기록 조회"
      - method: POST
        path: /rooms/{room_id}/messages
        description: "메시지 전송"
      - method: POST
        path: /rooms/{room_id}/images
        description: "이미지 업로드"
    websocket:
      - path: /ws/{room_id}
        description: "WebSocket 실시간 채팅"
        params:
          - user_id: 사용자 ID
    health:
      - method: GET
        path: /health
        description: "헬스체크"

external_integrations:
  kakao_oauth:
    type: OAuth 2.0
    endpoints:
      token: https://kauth.kakao.com/oauth/token
      user_info: https://kapi.kakao.com/v2/user/me

  toss_payments:
    type: Payment Gateway
    base_url: https://api.tosspayments.com
    version: v1
    auth: Basic (secret_key base64)
    endpoints:
      payments: /v1/payments
      confirm: /v1/payments/confirm

  aws_s3:
    type: Object Storage
    usage: 사용자 메모 JSON 저장
    path_pattern: "user_updates/{user_id}.json"

  naver_maps:
    type: Map/Search API
    base_url: https://openapi.naver.com/v1/search/local.json
    auth: X-Naver-Client-Id, X-Naver-Client-Secret
    endpoints:
      local_search: /v1/search/local.json
    rate_limit: 25000/day

  firebase_fcm:
    type: Push Notification
    usage: FCM 푸시 알림 전송
    auth: Firebase Admin SDK (서비스 계정)
    features:
      - 단일 알림 전송
      - 배치 알림 전송
      - 알림 유형별 템플릿

environment_variables:
  login-service:
    required:
      - KAKAO_REST_API_KEY
      - KAKAO_CLIENT_SECRET
      - KAKAO_REDIRECT_URI
      - USER_SERVICE_URL
      - JWT_SECRET
    optional:
      - ADMIN_KAKAO_IDS  # 쉼표로 구분된 허용 관리자 카카오 ID 목록

  user-service:
    required:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET_NAME
    optional:
      - DB_PORT  # default: 5432

  pay-service:
    required:
      - TOSS_CLIENT_KEY
      - TOSS_SECRET_KEY
      - USER_SERVICE_URL
    optional: []

  place-service:
    required:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - NAVER_CLIENT_ID
      - NAVER_CLIENT_SECRET
    optional:
      - DB_PORT  # default: 5432

  notification-service:
    required:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - FIREBASE_CREDENTIALS_JSON  # Base64 encoded
    optional:
      - DB_PORT  # default: 5432

  chat-service:
    required:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET_NAME
      - NOTIFICATION_SERVICE_URL
    optional:
      - DB_PORT  # default: 5432

constraints:
  scale: "DAU ~100 (MVP)"
  budget: "$50/월 이하"
  infrastructure: "AWS 유지"

conventions:
  coding:
    - "FastAPI 라우터 패턴 사용"
    - "Pydantic 모델로 요청/응답 검증"
    - "환경변수로 설정 관리"
    - "async/await 비동기 처리"
  naming:
    - "파일명: snake_case"
    - "클래스명: PascalCase"
    - "함수명: snake_case"
    - "상수명: UPPER_SNAKE_CASE"
  api:
    - "RESTful 엔드포인트"
    - "JSON 응답 형식"
    - "관리자 API는 /admin 프리픽스"
  security:
    - "관리자 API는 JWT 검증 필수"
    - "민감 정보는 환경변수로 관리"
    - "CORS 허용 도메인 제한"

dev_commands:
  build: "docker-compose build"
  run: "docker-compose up"
  run_detached: "docker-compose up -d"
  logs: "docker-compose logs -f"
  stop: "docker-compose down"
